export const RoutePaths = {
  LOGIN: "/login",
  LOGIN_CARD: "/login/login-card",
  DASHBOARD: "/dashboard",
  EULA: "/login/eula",
  GENERAL_MESSAGE: "/login/general-message",
  PRIVACY_POLICY: "/login/privacy-policy",
  FORGET_PASSWORD: "/login/forget-password",
  FORGET_PASSWORD_CONFIRM: "/login/forget-password-confirm",
  CHANGE_PASSWORD: "/login/change-password",
  CHANGE_PASSWORD_CONFIRM: "/login/change-password-confirm",
  DYNAMIC_LOADER: "/login/dynamic-loader"
};

export const SpecificPaths = {
  LOGIN: "login",
  LOGIN_CARD: "login-card",
  CLASSLINK_LOGIN: "classlink-login",
  CLEVER_LOGIN: "clever-login",
  DASHBOARD: "dashboard",
  EULA: "eula",
  GENERAL_MESSAGE: "general-message",
  PRIVACY_POLICY: "privacy-policy",
  FORGET_PASSWORD: "forget-password",
  FORGET_PASSWORD_CONFIRM: "forget-password-confirm",
  CHANGE_PASSWORD: "change-password",
  CHANGE_PASSWORD_CONFIRM: "change-password-confirm",
  DYNAMIC_LOADER: "dynamic-loader",
  VALUE_PROPOSION: "value-prop",
  CHOOSE_CLASS: "choose-class",
  VIEW_RATE_RECORDING: "view-rate-recording",
  VIEW_REPORTS: "view-reports",
  MANAGE_CLASS: "manage-class",
  EXPLORE_WEPLAYSMART: "explore-weplaysmart",
  SETTINGS: "settings",
  GAMEANIMATION: "game-animation",
};
