import { passwordMinLength } from "./Login.constants";

export const UiLables = {
    LABELS: {
    PRIVACY_POLICY: 'Privacy Policy',
    EULA: 'EULA',
    EULA_HEADING: 'End User License Agreement',
    VERSION: 'Version',
    ALL_RIGHTS_RESERVED: 'All Rights Reserved.',
    EXIT_TO_DESKTOP: 'Exit to Desktop',
    YES: 'Yes',
    NO: 'No',
    LOADING: 'Loading...',
    ARE_YOU_SURE_TO_EXIT: 'Are you sure you want to exit IgniteTable',
    ARE_YOU_SURE_TO_LOGOUT: 'Are you sure you want to log out',
    EMAIL_ADDRESS: 'Email Address',
    PASSWORD: 'Password',
    EMAIL_PLACEHOLDER: 'user@example.com',
    PASSWORD_PLACEHOLDER: 'Please enter your password.',
    FORGOT_PASSWORD: 'Forgot Password',
    LOG_IN: 'Log In',
    LOG_OUT: 'Log Out',
    RESET_YOUR_PASSWORD: 'Reset Your Password',
    RESET_PASSOWPRD_INFO: `Enter your email address, and we'll send you a link to reset your password.`,
    SET_A_NEW_PASSWORD: 'Set a New Password',
    SEND_ME_A_LINK: 'Send Me a Link',
    RETURN_TO_LOGIN: 'Return to Login',
    CHECK_YOUR_EMAIL: 'Check Your Email',
    FORGOT_PASSWORD_INFO1: 'An email has been sent to you from us at',
    FORGOT_PASSWORD_INFO2: `Please follow the instructions provided to reset your password.`,
    FORGOT_PASSWORD_INFOFOOTER1: `Did not receive the email?`,
    FORGOT_PASSWORD_INFOFOOTER2: `Check your spam folder, or contact Hatch support at:`,
    PASSWORD_UPDATED: 'Password Updated!',
    CHANGE_PASSWORD_CONFIRM_INFO:
      'Your password has been successfully updated.',
    CHANGE_PASSWORD_CONFIRM_SECTION: {
      FIRST: 'Please press the',
      CONTINUE: 'Continue',
      LAST: `to enter IgniteTable's cooperative learning environment!`,
    },
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    NEWPASSWORD_PLACEHOLDER: 'Please enter a new password.',
    CONFIRMPASSWORD_PLACEHOLDER: 'Please reenter your password.',
    CHANGE_PASSWORD_HEADER: 'Set a New Password',
    CHANGE_PASSWORD: 'Change Password',
    LOADING_ELLIPSIS: 'Loading...',
    DOWNLOADING_FILES: 'Downloading files',
    DEVICE_ID: 'Device ID',
    OS: 'OS',
    SCREEN_RESOLUTION: 'Screen Resolution',
    TOTAL_MEMORY: 'Total Memory',
    FREE_MEMORY: 'Free Memory',
    TOTAL_STORAGE: 'Total Storage',
    FREE_STORAGE: 'Free Storage',
    NETWORK_UPLOAD_SPEED: 'Network Upload Speed',
    NETWORK_DOWNLOAD_SPEED: 'Network Download Speed',
    BACK: 'Back',
    SETTINGS: 'Settings',
    CHECK: 'Check',
    FOR_UPDATES: 'For Updates',
    SYSTEM: 'System',
    INFO: 'Information',
    CANCEL: 'Cancel',
    AND: 'and',
    DOT: '.',
    UPGRADE_INFO: 'Upgrade Information',
    DYNAMIC_LOADER_MESSAGES: {
      CHECK_BUNDLES: 'Checking if latest game bundles are available...',
      BUNDLES_AVAILABLE: 'Game bundles are available, loading...',
      FETCHING_BUNDLES: 'Fetching game bundles to download...',
      DOWNLOADING_BUNDLES: 'Downloading game bundles...',
      UNZIPPING_BUNDLES: 'Unzipping game bundles...',
    },
    ONLY_AVAILABLE_WITH_UPGRADE: 'Only Available with Upgrade',
    CONFIRM: 'Confirm',
    REAUTH_COGNITO_TEXT: 'Please enter your password to continue. ',
    REAUTH_COGNITO_TEXT2:
      'If this is not you, please log out and log in again.',
    REAUTH_CLEVER_TEXT1:
      'Please log in to confirm your identity. If you do not know the',
    REAUTH_CLEVER_TEXT2:
      'user name and password of the current user, please log out and log in again.',
    CHECK_FOR_UPDATES_TEXT1:
      'Updates are downloaded automatically, but if you would like to',
    CHECK_FOR_UPDATES_TEXT2:
      'manually check for updates, press the button below.',
    DOWNLOADING_UPDATES: 'Downloading Updates',
    UPDATES_DOWNLOADED: 'Updates Downloaded ',
    NEW_UPDATES_FOUND: 'New Updates Found',
    NO_UPDATES_FOUND: 'No Updates Found.',
    CHECK_FOR_UPDATES_AND_DOWNLOAD: 'Check for Updates and Download',
    INSTALL_UPDATES: 'Install Updates',
    DOWNLOAD_UPDATES: 'Download Updates',
    LAST_CHECKED_FOR_UPDATES: 'Last checked for Updates :',
    INSTALLED_SOFTWARE_VERSION: 'Installed Software version : ',
    DATE_OF_INSTALL: 'Date of Install : ',
  },
  MESSAGES: {
    EULA_UPDATE: {
      HEADER: 'We have updated our End User License Agreement',
      SUBHEADER: 'Select the gear to continue.',
      P1: 'Select the gear in the bottom-right corner of the screen to enter the Teacher Area where you will verify your identity and review the new agreement.',
      P2: 'You must accept the new agreement to continue using this software.',
    },
    LICENSE_EXPIRE: {
      HEADER: 'Your License Has Expired',
      SUBHEADER: '  ',
      P1: 'Please contact your administrator to renew your license.',
      P2: '  ',
      P3: '  ',
      PRIMARYBTN: 'Exit App',
      SECONDARYBTN: 'Log Out',
    },
    CHILD_FACING_ERROR: {
      HEADER: 'Oops! It Looks Like Something Went Wrong',
      SUBHEADER: '  ',
      P1: 'Select the gear in the bottom right corner of the screen for more information.',
      P2: '  ',
      P3: '  ',
      PRIMARYBTN: '',
      SECONDARYBTN: '',
    },
    GAME_ERROR: {
      HEADER: 'Oops! It Looks Like Something Went Wrong',
      SUBHEADER: '  ',
      P1: 'Select the gear in the bottom right corner of the screen for more information.',
      P2: '  ',
      P3: '  ',
      PRIMARYBTN: '',
      SECONDARYBTN: '',
    },
    UPDATE_AVAILABLE_ERROR: {
      HEADER: 'Your Update is Ready to Install!',
      SUBHEADER: 'Please wait: Your app will close momentarily',
      P1: 'Your app will close and your update will be installed. The app will restart automatically when it is ready.',
      P2: '  ',
      P3: '  ',
      PRIMARYBTN: 'Continue',
      SECONDARYBTN: '',
    },
    API_ERROR_EMAIL_UPDATE: {
      HEADER: 'Your Login Information has Changed',
      SUBHEADER: 'Please log in again with your email and password',
      P1: 'If you did not make this change, please contact your administrator to verify your login details.',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Continue',
      SECONDARYBTN: '',
    },
    UPDATE_IS_DOWNLOADING_ERROR: {
      HEADER: 'Please Wait...',
      SUBHEADER: 'Please wait: Your app is getting updated',
      P1: 'Downloading...',
      P2: '  ',
      P3: '  ',
      PRIMARYBTN: '',
      SECONDARYBTN: '',
    },
    CLASSLINK_USER_NOT_FOUND: {
      HEADER: 'Something Went Wrong',
      SUBHEADER:
        'Please contact your administrator or Hatch support with the following information',
      P1: 'Classlink user not authorized to use Single Sign On (SSO) with IgniteTable by Hatch',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Back',
      SECONDARYBTN: 'Exit App',
    },
    CLEVER_USER_NOT_FOUND: {
      HEADER: 'Something Went Wrong',
      SUBHEADER:
        'Please contact your administrator or Hatch support with the following information',
      P1: 'Clever user not authorized to use Single Sign On (SSO) with IgniteTable by Hatch',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Back',
      SECONDARYBTN: 'Exit App',
    },
    CLASSLINK_LEAD_TEACHER_NOT_ALLOWED: {
      HEADER: 'Something Went Wrong',
      SUBHEADER:
        'Please contact your administrator or Hatch support with the following information',
      P1: 'Only teachers can log in here. Admins, please visit Insights by Hatch',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Back',
      SECONDARYBTN: 'Exit App',
    },
    NO_INTERNET_ERROR: {
      HEADER: 'Something Went Wrong',
      SUBHEADER: 'No Internet Connection Detected',
      P1: 'Please exit the app and connect your device to the internet to continue or select ‘Try Again’ to check your internet connection again',
      P2: '  ',
      P3: '  ',
      PRIMARYBTN: 'Exit App',
      SECONDARYBTN: 'Try Again',
    },
    AWS_COGNITO_ERROR: {
      HEADER: 'Something Went Wrong',
      SUBHEADER: 'Please try again later',
      P1: 'If the problem continues, please contact your administrator or Hatch support with the following information:',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Back',
      SECONDARYBTN: 'Exit App',
    },
    API_FAILED: {
      HEADER: 'Something Went Wrong',
      SUBHEADER: 'Please try again later',
      P1: 'If the problem continues, please contact your administrator or Hatch support with the following information:',
      P2: '  ',
      P3: '  ',
      PRIMARYBTN: 'Exit App',
      SECONDARYBTN: 'Log Out',
    },
    UPGRADE_INFO: {
      HEADER: 'Learn More About Your Upgrade Options',
      SUBHEADER:
        'Your organization has limited access to reports and the full suite of available games.',
      P1: 'Please reach out to your administrator to inquire about upgrading. Thank you!',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Upgrade Information',
      SECONDARYBTN: 'Continue',
    },
    REAUTH_GENERAL_MESSAGE: {
      HEADER: 'Something Went Wrong',
      SUBHEADER:
        'The given user does not match the current login or is not in our system.',
      P1: 'Please check your user name and password and try again. If you do not know the user name and password for the current user, please log out and log back in.',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Back',
      SECONDARYBTN: '',
    },
    INACTIVITY_GENERAL_MESSAGE: {
      HEADER: 'Are You Still Using Insights?',
      SUBHEADER:
        'Select Yes if you would like to continue using Insights.',
      P1: 'If no selection is made the Teacher Area will close after 10 seconds to prevent accidental changes.',
      P2: '',
      P3: '',
      PRIMARYBTN: 'Yes',
      SECONDARYBTN: '',
    },
    GAME_OVER: 'Game Over',
  },
  VALIDATIONS: {
    EMAIL_NOT_VALID:
      'Incorrect email format. Please try again using user@domain.com format.',
    PASSWORD_LICIENCE_EXPIRED:
      'Your license has expired. Please contact your administrator.',
    PASSWORD_INCORRECT1: 'Incorrect email or password. Please try again or',
    PASSWORD_INCORRECT2: 'reset it',
    ONLY_TEACHER_CAN_USE_APP:
      'Only teachers can log in here. Admins, please visit Insights by Hatch.',
    EMAIL_INCORRECT: 'Incorrect email. Please try again.',
    MIN_PASSWORD_ERROR: `Password must be ${passwordMinLength} or more characters. Please try again.`,
    PASSWORD_MATCH_ERROR: 'Passwords must match. Please try again.',
    API_ERROR: 'Something went wrong, please try again.',
  },
}

export default UiLables;